apiVersion: v1
kind: Namespace
metadata:
  name: skyscrubber-namespace 

---
# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: skyscrubber-namespace
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb
          image: melnikovya/mongodb:latest  # замените на ваш образ MongoDB
          ports:
            - containerPort: 27017

---
# FastAPI Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: skyscrubber-namespace
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: skyscrubber
          image: melnikovya/skyscrubber:latest  # замените на ваш образ FastAPI
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  namespace: skyscrubber-namespace
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  # или используйте другий тип службы в зависимости от вашей конфигурации
